#49 [Hook] add: unassign shortener action and fix edit action
Eoxia/EasyURL pull request #54
Opened 2024-04-04 15:02 UTC by nicolas-eoxia

2024-04-05 14:19 UTC, evarisk-micka requested changes

2024-04-05 14:19 UTC, evarisk-micka commented on langs/fr_FR/easyurl.lang
> +UnassignShortenerSuccess  = Désaffectation du raccourcissement d'URL <strong>%s</strong>
"Désaffectation du raccourci URL"

2024-04-22 12:45 UTC, evarisk-charles approved these changes

2024-04-24 07:58 UTC, evarisk-micka requested changes

2024-04-24 07:58 UTC, evarisk-micka commented on langs/fr_FR/easyurl.lang
> +ObjectUnAssignTrigger     = %s %s désaffectée
Si c'est UN url désaffecté alors il n'y a pas de e à la fin

2024-04-24 07:58 UTC, evarisk-micka commented on langs/fr_FR/easyurl.lang
> +ObjectUnAssignTrigger     = %s %s désaffectée
Aussi si c'est une traduction générique d'objet elle devrait plutôt aller sur Saturne

2024-04-24 07:58 UTC, evarisk-micka commented
A part une imprécision au niveau du fichier .lang le reste de la PR est bonne à merge, il faut juste bouger la traduction de place

2025-02-18 05:21 UTC, closed without merging